const PDFDocument = require('pdfkit');
const { getLogs } = require('./buildLogService');

function escapeMd(text) {
  return String(text ?? '').replace(/`/g, '\\`').replace(/\|/g, '\\|');
}

async function buildLogsMarkdown(project) {
  const logs = await getLogs({ projectId: project.id, limit: 2000 });
  const lines = [];
  lines.push(`# Build Logs — ${project.title}`);
  lines.push('');
  lines.push(`- **Status:** ${project.status}`);
  lines.push(`- **Stack:** ${project.stack}`);
  lines.push(`- **Created:** ${project.createdAt.toISOString()}`);
  lines.push('');
  lines.push('| Time | Level | Source | Message |');
  lines.push('| --- | --- | --- | --- |');
  for (const log of logs) {
    lines.push(`| ${log.createdAt.toISOString()} | ${log.level} | ${escapeMd(log.source)} | ${escapeMd(log.message)} |`);
  }
  return lines.join('\n');
}

async function projectMarkdown(project, agents, files) {
  const lines = [];
  lines.push(`# ${project.title}`);
  lines.push('');
  lines.push(`> ${project.description || 'No description provided.'}`);
  lines.push('');
  lines.push('## Overview');
  lines.push('');
  lines.push(`- **Status:** ${project.status}`);
  lines.push(`- **Stack:** ${project.stack}`);
  lines.push(`- **Generated files:** ${files.length}`);
  lines.push(`- **Created:** ${project.createdAt.toISOString()}`);
  lines.push('');
  lines.push('## AI Agents');
  lines.push('');
  lines.push('| Agent | Status | Progress |');
  lines.push('| --- | --- | --- |');
  for (const a of agents) {
    lines.push(`| ${escapeMd(a.displayName || a.role)} | ${a.status} | ${a.progress}% |`);
  }
  lines.push('');
  lines.push('## File Structure');
  lines.push('');
  lines.push('```');
  const tree = buildFileTree(files.map((f) => f.path));
  lines.push(tree);
  lines.push('```');
  return lines.join('\n');
}

function buildFileTree(paths) {
  const root = {};
  for (const p of paths) {
    const parts = p.split('/');
    let node = root;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isLast = i === parts.length - 1;
      if (isLast) {
        node[part] = null;
      } else {
        node[part] = node[part] || {};
        node = node[part];
      }
    }
  }
  const render = (node, prefix) => {
    const out = [];
    const entries = Object.entries(node).sort(([a], [b]) => (node[b] === null ? 1 : -1) - (node[a] === null ? 1 : -1) || a.localeCompare(b));
    for (const [name, child] of entries) {
      out.push(`${prefix}${child === null ? '📄 ' : '📁 '}${name}`);
      if (child !== null) {
        out.push(...render(child, `${prefix}  `));
      }
    }
    return out;
  };
  return render(root, '').join('\n');
}

async function buildPdf(documentTitle, md) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, bufferPages: true });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(22).fillColor('#0f172a').text(documentTitle, { continued: false });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#64748b').text(`Generated by DevForge AI — ${new Date().toISOString()}`);
    doc.moveDown(1);

    for (const line of md.split('\n')) {
      if (line.startsWith('# ')) {
        doc.fontSize(18).fillColor('#0f172a').text(line.slice(2));
        doc.moveDown(0.5);
      } else if (line.startsWith('## ')) {
        doc.fontSize(14).fillColor('#1e293b').text(line.slice(3));
        doc.moveDown(0.4);
      } else if (line.startsWith('> ')) {
        doc.fontSize(10).fillColor('#475569').text(line.slice(2));
        doc.moveDown(0.4);
      } else if (line.startsWith('```')) {
        continue;
      } else if (line.startsWith('| ')) {
        doc.fontSize(9).fillColor('#334155').text(line.replace(/`/g, ''));
      } else if (line.trim()) {
        doc.fontSize(10).fillColor('#334155').text(line);
      } else {
        doc.moveDown(0.3);
      }
    }

    doc.end();
  });
}

module.exports = { buildLogsMarkdown, projectMarkdown, buildPdf };
